### PR TITLE
Bug fixes [FIXED]

### PR DESCRIPTION
**Pull request by tchan128**
Current FIxes:

- Added `.env` file
- Added textarea padding and char count for PRIVATE CONVO FORM
Screenshot 2024-03-24 at 11 08 47 PM
- When "+ new public conversation" is clicked, it anchors it to the header so the public form shows
- When user clicks on public conversation, it will automatically scroll to the top to display the conversation
- Changed PRIVATE convo form text to: "Your bench awaits..."
- When logo is clicked on the homepage it doesn't render back the "welcome to soul bench" component -> now it does; 
    - this means you press on a public convo and press logo -> home
    - this means mid-convo making and press logo -> home
- Buddy's name is populated on the my bench card
```
 buddy: user.buddy.username, 
```
Screenshot 2024-03-25 at 1 18 00 AM
Screenshot 2024-03-25 at 1 18 09 AM
- When user clicks on add new conversation and then presses on an existing public conversation it stays on the conversation creation form and doesn't go to the conversation (BUG FIXED)
```
setIsStartingPublicConversation(false)
```
is added to the `handleConversationClick` function so that it doesn't keep conditionally the conversation form
- When user submits PRIVATE conversation, it renders immediately, primarily changed if there isn't conversationID then it refetches:

```
  useEffect(() => {
    if (!conversationId) {
      refetchUser();
      refetchConversation;
    }
  }, [conversationId, refetchUser, refetchConversation]);
```
- Toast added to private conversation form
   - If over 500 for details and over 50 for title
- `required` added to choosing of what to talk about and also for all fields in private confirmation form
- No buddy flow - WAS just rendering the form again, NOW renders the modal:
Screenshot 2024-03-25 at 3 13 09 AM
- When private conversation is rendered, buddy name is displayed in title card
Screenshot 2024-03-25 at 3 44 18 AM
- Different color for comments
Screenshot 2024-03-25 at 4 20 22 AM

### CODE REVIEW

**Review by kwubbenhorst — APPROVED** [review]
charCount looks great.  I keep wondering about "Let's put things to bench". I've heard of "let's put things to bed" (ie. let's settle matters) but I'm not familiar with what putting things to bench might mean.  Maybe  "Stake out your bench", "Grab a seat on your bench",  "Your bench awaits..." "Your bench beckons..." ???

**Comment by tchan128** [comment]
> charCount looks great. I keep wondering about "Let's put things to bench". I've heard of "let's put things to bed" (ie. let's settle matters) but I'm not familiar with what putting things to bench might mean. Maybe "Stake out your bench", "Grab a seat on your bench", "Your bench awaits..." "Your bench beckons..." ???

I like "Your bench awaits...", will change that on my newest push later! @kwubbenhorst

**Review by kwubbenhorst — APPROVED** [review]
Looks great!

**Comment by tchan128** [comment]
@kwubbenhorst Let's try to get this merge in (I presume there will be merge conflicts we have to resolve after this is merged for the PWA and edit comment branch). We can then take a look at those and try and get that up and running. Thoughts?

Happy to run through the changes I made beginning of class today

**Review by Jasmineleeyt — APPROVED** [review]
lgtm!

**Pull request merged**
