### PR TITLE
Polishing UI - ongoing

### LINKED ISSUE #34: Polish UI
currently coded with bootstrap
bootstrap -> tailwind

### PR DESCRIPTION
**Pull request by tchan128**
Current updates:

- 1st commit:  Corrected sizing of the screen (removed extra columned space on the right)
Screenshot 2024-03-23 at 6 07 11 PM

- 2nd commit: Testing our blue color scheme
Screenshot 2024-03-23 at 7 13 00 PM 1
Screenshot 2024-03-23 at 7 13 18 PM

- 3rd commit: Modified login page
Screenshot 2024-03-23 at 7 42 19 PM

- 4th commit: Modified role page

Screenshot 2024-03-23 at 8 36 30 PM

- 5+ commits: conversations, sign ups, and resource
Screenshot 2024-03-24 at 1 02 21 AM

Screenshot 2024-03-24 at 1 02 47 AM

Screenshot 2024-03-24 at 1 03 07 AM
Screenshot 2024-03-24 at 1 03 15 AM

18 commit: updated home page, created an anchor tag to the pavilion on the home page, and created about page
Screenshot 2024-03-24 153556
Screenshot 2024-03-24 153606

Fixed log out problem

### CODE REVIEW

**Review by kwubbenhorst — APPROVED** [review]
looks good

**Review by kwubbenhorst — APPROVED** [review]
I love the bench in commit #3! Blue colour scheme is nice -- restful!

**Review by kwubbenhorst — APPROVED** [review]
Polishing up beautifully!! Such a great look and feel, mellow and reflective.

**Comment by tchan128** [comment]
FYI @kwubbenhorst @Jasmineleeyt @ae-andre 

Commit #6e19b1e fixes the issue of my bench. When someone presses on my bench it will always refresh the page to bring them back to the cards. Check it out here: https://share.vidyard.com/watch/1x4ziRB1iFfGF8EoCSJviS? 

Also same for listener so no manual refreshing of page is needed.

**Comment by kwubbenhorst** [comment]
> FYI @kwubbenhorst @Jasmineleeyt @ae-andre
> 
> Commit #6e19b1e fixes the issue of my bench. When someone presses on my bench it will always refresh the page to bring them back to the cards. Check it out here: https://share.vidyard.com/watch/1x4ziRB1iFfGF8EoCSJviS?
> 
> Also same for listener so no manual refreshing of page is needed.

That's wonderful.  Is this code included in the UI polishing pull request?  I'm happy to merge it anytime.  Left my approving review.  Needs one more.

**Comment by tchan128** [comment]
@kwubbenhorst 

> That's wonderful. Is this code included in the UI polishing pull request? I'm happy to merge it anytime. Left my approving review. Needs one more.

Happy to merge it so everyone can see the newest UI! We are still working on a few things but most of it is poslished!!

**Review by Jasmineleeyt — APPROVED** [review]

**Pull request merged**
